### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AmingWu** [debadeepta/vnla#2]
Hey,
When I run your vnla code, there is an error.

python src/driver/driver.py fzynW3qQPVF 8e8d691920d14c8e8a3a2371edeaa2bd 1.04

Traceback (most recent call last):
  File "src/driver/driver.py", line 31, in <module>
    sim.newEpisode(house_id, view_id, heading, 0)
ValueError: MatterSim: Could not open skybox files at: ./data/v1/scans/fzynW3qQPVF/matterport_skybox_images/8e8d691920d14c8e8a3a2371edeaa2bd_skybox*_sami.jpg

My data have included the ./data/v1/scans/fzynW3qQPVF/matterport_skybox_images/8e8d691920d14c8e8a3a2371edeaa2bd_skybox0_sami.jpg - 8e8d691920d14c8e8a3a2371edeaa2bd_skybox5_sami.jpg

**Comment by khanhptnk** [comment]
Did you use the v0.1 of the Matterport3d Simulator? And in what directory did you run the python command from?

**Comment by AmingWu** [comment]
Yes, I have run the demo of Matterport3d Simulator successfully. And I have run your train code successfully.

**Comment by khanhptnk** [comment]
Should we close this thread. Is there anything else I can help with?

**Comment by AmingWu** [comment]
But I cannot run your driver.py successfully.

**Comment by AmingWu** [comment]
The command is from code/src/driver/driver.py

**Comment by AmingWu** [comment]
I want to know how this path of ./data/v1/scans/fzynW3qQPVF/matterport_skybox_images/8e8d691920d14c8e8a3a2371edeaa2bd_skybox*_sami.jpg is generated.

**Comment by khanhptnk** [comment]
Can you try to do "ls ./data/v1/scans/fzynW3qQPVF/matterport_skybox_images/8e8d691920d14c8e8a3a2371edeaa2bd_skybox*_sami.jpg" from the current folder and paste the output here.

**Comment by khanhptnk** [comment]
Did you run `ln -s <Matterdata> data` in the `code` directory?

**Comment by AmingWu** [comment]
OK, I have solved this problem. Thank you.

**Comment by khanhptnk** [comment]
No problem. Good luck!

**Comment by AmingWu** [comment]
OK. I only run ln -s <Matterdata> data in the code directory. Could you give a code to show the result of Fig. 1(a) of your paper?

**Comment by khanhptnk** [comment]
That figure is actually a screenshot from the Matterport3D paper: https://arxiv.org/pdf/1709.06158.pdf (see page 17).
