### ISSUE TITLE
Broken dropbox link while downloading data.

### ISSUE THREAD

**Issue by vdorbala** [debadeepta/vnla#3]
Hi.
While running your "download.sh" file in the data folder, it points to a broken dropbox link for Resnet-152-Imagenet.
Could you please fix this?

Thanks!

**Comment by khanhptnk** [comment]
Thanks for noticing! The link has been fixed. The features are not maintained by us, so if the link would ever change in the future, please visit: https://github.com/peteanderson80/Matterport3DSimulator#precomputing-resnet-image-features and click on "ResNet-152-imagenet features [380K/2.9GB]" to get the latest link.
